# 🎵 Yuna Music - Docker Compose Configuration
# For easy deployment on SillyDev and other platforms

version: '3.8'

services:
  yuna-music:
    build: .
    container_name: yuna-music-bot
    restart: unless-stopped
    
    # Environment variables (override in .env file)
    environment:
      - NODE_ENV=production
      - NODE_OPTIONS=--max-old-space-size=1024
    
    # Volume mounts for persistence
    volumes:
      - ./logs:/app/logs
      - ./data:/app/data
    
    # Network configuration
    networks:
      - yuna-network
    
    # Resource limits
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '0.5'
        reservations:
          memory: 512M
          cpus: '0.25'
    
    # Health check
    healthcheck:
      test: ["CMD", "npm", "run", "test"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

networks:
  yuna-network:
    driver: bridge

# Optional: MongoDB service (if not using external MongoDB)
# services:
#   mongodb:
#     image: mongo:5.0
#     container_name: yuna-mongodb
#     restart: unless-stopped
#     environment:
#       MONGO_INITDB_ROOT_USERNAME: admin
#       MONGO_INITDB_ROOT_PASSWORD: password123
#     volumes:
#       - mongodb_data:/data/db
#     networks:
#       - yuna-network
#     ports:
#       - "27017:27017"

# volumes:
#   mongodb_data: